
# min number of images for each partition
min_element_training: 1
min_element_test: 1
min_element_validation: 1

# partitioning percentage
percentage_training : 0.70
percentage_test : 0.15
percentage_validation : 0.15

# Super-classes
super_classes:
    nc: 46
    names: [ 'speed limit 20 (prohibitory)',
             'speed limit 30 (prohibitory)',
             'speed limit 50 (prohibitory)',
             'speed limit 60 (prohibitory)',
             'speed limit 70 (prohibitory)',
             'speed limit 80 (prohibitory)',
             'restriction ends 80 (other)',
             'speed limit 100 (prohibitory)',
             'speed limit 120 (prohibitory)',
             'no overtaking (prohibitory)',
             'no overtaking (trucks) (prohibitory)',
             'priority at next intersection (danger)',
             'priority road (other)',
             'give way (other)',
             'stop (other)',
             'no traffic both ways (prohibitory)',
             'no trucks (prohibitory)',
             'no entry (other)',
             'danger (danger)',
             'bend left (danger)',
             'bend right (danger)',
             'bend (danger)',
             'uneven road (danger)',
             'slippery road (danger)',
             'road narrows (danger)',
             'construction (danger)',
             'traffic signal (danger)',
             'pedestrian crossing (danger)',
             'school crossing (danger)',
             'cycles crossing (danger)',
             'snow (danger)',
             'animals (danger)',
             'restriction ends (other)',
             'go right (mandatory)',
             'go left (mandatory)',
             'go straight (mandatory)',
             'go right or straight (mandatory)',
             'go left or straight (mandatory)',
             'keep right (mandatory)',
             'keep left (mandatory)',
             'roundabout (mandatory)',
             'restriction ends (overtaking) (other)',
             'restriction ends (overtaking (trucks)) (other)',
             'prohibitory',
             'danger',
             'mandatory' ]
classes:
    nc: 46
    names: [ 'speed limit 20 (prohibitory)',
             'speed limit 30 (prohibitory)',
             'speed limit 50 (prohibitory)',
             'speed limit 60 (prohibitory)',
             'speed limit 70 (prohibitory)',
             'speed limit 80 (prohibitory)',
             'restriction ends 80 (other)',
             'speed limit 100 (prohibitory)',
             'speed limit 120 (prohibitory)',
             'no overtaking (prohibitory)',
             'no overtaking (trucks) (prohibitory)',
             'priority at next intersection (danger)',
             'priority road (other)',
             'give way (other)',
             'stop (other)',
             'no traffic both ways (prohibitory)',
             'no trucks (prohibitory)',
             'no entry (other)',
             'danger (danger)',
             'bend left (danger)',
             'bend right (danger)',
             'bend (danger)',
             'uneven road (danger)',
             'slippery road (danger)',
             'road narrows (danger)',
             'construction (danger)',
             'traffic signal (danger)',
             'pedestrian crossing (danger)',
             'school crossing (danger)',
             'cycles crossing (danger)',
             'snow (danger)',
             'animals (danger)',
             'restriction ends (other)',
             'go right (mandatory)',
             'go left (mandatory)',
             'go straight (mandatory)',
             'go right or straight (mandatory)',
             'go left or straight (mandatory)',
             'keep right (mandatory)',
             'keep left (mandatory)',
             'roundabout (mandatory)',
             'restriction ends (overtaking) (other)',
             'restriction ends (overtaking (trucks)) (other)',
             'prohibitory',
             'danger',
             'mandatory']


mapping_c_sc:
    0: 0
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 8
    9: 9
    10: 10
    11: 11
    12: 12
    13: 13
    14: 14
    15: 15
    16: 16
    17: 17
    18: 18
    19: 19
    20: 20
    21: 21
    22: 22
    23: 23
    24: 24
    25: 25
    26: 26
    27: 27
    28: 28
    29: 29
    30: 30
    31: 31
    32: 32
    33: 33
    34: 34
    35: 35
    36: 36
    37: 37
    38: 38
    39: 39
    40: 40
    41: 41
    42: 42
    43: 43
    44: 44
    45: 45
