path: "./Dataset/Dataset 10.000 images"
# path: "./Dataset/Dataset 800 images"
train: "train/images"
val: "val/images"
test: "test/images"

#Classes
nc: 7

names: ['prohibitory', 'danger', 'mandatory', 'priority road', 'give way', 'stop', 'no entry']